-   id: prettier
    name: prettier
    description: ''
    entry: prettier --write --list-different --ignore-unknown
    language: node
    stages: [commit, merge-commit, push, manual]
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["prettier@3.0.0-alpha.6"]
    minimum_pre_commit_version: '0'
